services:
  unifi:
    image: jacobalberty/unifi:latest
    networks: [veve]
    container_name: unifi
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./data:/unifi
    ports:
      - 8080:8080        # inform port – AP se sem připojují (HTTP)
      - 8443:8443        # webové UI controlleru (HTTPS)
      - 3478:3478/udp    # STUN – detekce NAT, důležité pro některé scénáře
      - 10001:10001/udp  # discovery – L2 broadcast adopce zařízení
      - 1900:1900/udp    # SSDP – discovery (často není nutné v čisté L2 síti)
      - 8843:8843        # HTTPS guest portal
      - 8880:8880        # HTTP guest portal
      - 6789:6789        # speed test (UniFi zařízení)
    restart: unless-stopped

networks:
  veve:
    external: true


