services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Prague
    extra_hosts:
      - "mqtt:127.0.0.1"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
